/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import classes.DBController;
import classes.Update;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class DevolverVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form DevolverVeiculo
     */
    public DevolverVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        placa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        recVeiculo = new javax.swing.JButton();
        isCarro = new javax.swing.JRadioButton();
        isMoto = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Receber Veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 15), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel8.setText("Placa");

        recVeiculo.setText("Receber Veículo");
        recVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recVeiculoActionPerformed(evt);
            }
        });

        buttonGroup1.add(isCarro);
        isCarro.setSelected(true);
        isCarro.setText("Carro");

        buttonGroup1.add(isMoto);
        isMoto.setText("Moto");

        jLabel9.setText("Tipo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(24, 24, 24))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(recVeiculo))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(isMoto)
                            .addComponent(isCarro))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(14, 14, 14)
                .addComponent(isCarro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isMoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(recVeiculo)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    DBController db = new DBController("dbTrab.db");
    private final List<List<String>> listaCarros= db.selectAllCarros();
    private final List<List<String>> listaMotos= db.selectAllMotos();
    private final List<List<String>> listaClientes= db.selectAllClientes();
    
    private boolean existsPlacaCarro(String placa) throws Exception{

        for(int i = 0; i < this.listaCarros.size(); i++)
        {
            if(listaCarros.get(i).get(6).equals(placa))
            {
                //Checa se já ta sendo alugado
                if(listaCarros.get(i).get(4).equals("Alugado"))
                {
                    return true;
                }
            }
        }
        return false;
    }
    private boolean existsPlacaMoto(String placa) throws Exception{
        for(int i = 0; i < this.listaMotos.size(); i++)
        {
            if(listaMotos.get(i).get(6).equals(placa))
            {
                //Checa se já ta sendo alugado
                if(listaMotos.get(i).get(4).equals("Alugado"))
                {
                    return true;
                }
            }
        }
        return false;
    }
    private String getClienteAlugandoCarro(String placa) throws Exception{
        for(int i = 0; i < this.listaCarros.size(); i++)
        {
           if(listaCarros.get(i).get(6).equals(placa))
           {
               return listaClientes.get(i).get(3);
           }
        }
        
        return "";
    }
    private String getClienteAlugandoMoto(String placa) throws Exception{
        for(int i = 0; i < this.listaMotos.size(); i++)
        {
           if(listaMotos.get(i).get(6).equals(placa))
           {
               return listaClientes.get(i).get(3);
           }
        }
        
        return "";
    }
       
    private void recVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recVeiculoActionPerformed
        if (isCarro.isSelected()){
               System.out.println(placa.getText());
            try {
                if (existsPlacaCarro(placa.getText()))
                {
                    Update app = new Update();
                    app.updateCarros("", placa.getText(), false);
                    String cpf = getClienteAlugandoCarro(placa.getText());
                    System.out.println("cpf: " + cpf);
                    app.updateClientes(cpf, "");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Placa inválida");
                }
            } catch (Exception ex) {
                Logger.getLogger(AlugarVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (isMoto.isSelected()){
            try {
                if (existsPlacaMoto(placa.getText()))
                {
                    Update app = new Update();
                    app.updateMotos("", placa.getText(), false);
                    String cpf = getClienteAlugandoMoto(placa.getText());
                    app.updateClientes(cpf, "");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Placa inválida");
                }
            } catch (Exception ex) {
                Logger.getLogger(AlugarVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        super.dispose();
    }//GEN-LAST:event_recVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevolverVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevolverVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevolverVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevolverVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DevolverVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton isCarro;
    private javax.swing.JRadioButton isMoto;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField placa;
    private javax.swing.JButton recVeiculo;
    // End of variables declaration//GEN-END:variables
}
